# Generated by Django 4.2.4 on 2023-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
