# Generated by Django 4.2.4 on 2023-09-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stage',
            new_name='state',
        ),
    ]
